apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  namespace: ci-cd
  labels:
    app: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
      - name: drone
        image: drone/drone
        ports:
        - containerPort: 80
        env:
        - name: DRONE_GITEA_SERVER
          value: "http://gitea" 
        - name: DRONE_GITEA_CLIENT_ID
          valueFrom: 
            secretKeyRef: 
              name: drone-gitea
              key: drone-gitea-client-id
        - name: DRONE_GITEA_CLIENT_SECRET
          valueFrom: 
            secretKeyRef: 
              name: drone-gitea
              key: drone-gitea-client-secret
        - name: DRONE_RPC_SECRET
          valueFrom: 
            secretKeyRef: 
              name: drone-rpc-secret
              key: drone-rpc-secret
        - name: DRONE_SERVER_HOST
          value: "drone"
        - name: DRONE_SERVER_PROTO
          value: "http"
        - name: DRONE_LOGS_DEBUG
          value: "true"
        - name: DRONE_LOGS_TRACE
          value: "true" 
        volumeMounts:
        - mountPath: /data
          name: dronedir
      volumes:
        - name: dronedir
          hostPath: #beware: works only in with single node
            path: /data/drone
            type: DirectoryOrCreate
